### ISSUE TITLE
C++ errors failed to build

### ISSUE THREAD

**Issue by Pi-Runner** [mit-dci/opencbdc-tx#35] opened 2022-02-06 17:01 UTC
### Affected Branch

Scanning dependencies of target crypto
[  4%] Building CXX object 3rdparty/crypto/CMakeFiles/crypto.dir/sha256_avx2.o
c++: error: unrecognized command line option '-mavx'
c++: error: unrecognized command line option '-mavx2'
make[2]: *** [3rdparty/crypto/CMakeFiles/crypto.dir/build.make:63: 3rdparty/crypto/CMakeFiles/crypto.dir/sha256_avx2.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:771: 3rdparty/crypto/CMakeFiles/crypto.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c mkdir build &&     cd build &&     cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .. &&     make' returned a non-zero code: 2
ERROR: Service 'shard0' failed to build : Build failed

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

Having trouble with the build got the error above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment] 2022-02-06 22:37
This looks like your compiler doesn't support AVX or AVX2. Can you provide some more details on what hardware/toolchain setup you have (e.g., the output of `lscpu` if on Linux, and `c++ --version` would be helpful)?

**Comment by Pi-Runner** [comment] 2022-02-07 00:27
I built it on a raspberry pi 4, using rasping version of linux.  Thank you for your help.

**Comment by HalosGhost** [comment] 2022-02-07 00:39
Ahh, that is unlikely to work. The code (in its current form) [assumes Linux x86_64](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docs/getting-started.md#can-i-contribute-without-using-docker-running-some-other-environment-etc).

We don't require this to stay the same and would happily accept changes to make the code portable to other platforms; if you'd be interested in helping out with that effort, we would welcome it!

**Comment by HalosGhost** [comment] 2022-02-07 15:19
@Pi-Runner I wanted to chime in and offer a possible work-around. I don't believe anything other than the sha256 implementation we leverage uses AVX or AVX2. So, the following patch should remove the need for AVX instruction sets:

```patch
diff --git a/3rdparty/crypto/CMakeLists.txt b/3rdparty/crypto/CMakeLists.txt
index 498335b..1962dcc 100644
--- a/3rdparty/crypto/CMakeLists.txt
+++ b/3rdparty/crypto/CMakeLists.txt
@@ -1,18 +1,15 @@
 project(crypto)
 
-add_library(crypto sha256_avx2.cpp
-                   sha256_shani.cpp
+add_library(crypto sha256_shani.cpp
                    sha256_sse4.cpp
                    sha256_sse41.cpp
                    sha256.cpp
                    siphash.cpp)
 target_include_directories(crypto PRIVATE ".." ".")
-set_source_files_properties(sha256_avx2.cpp PROPERTIES COMPILE_FLAGS
-                                            "-DENABLE_AVX2 -mavx -mavx2")
 set_source_files_properties(sha256_shani.cpp PROPERTIES COMPILE_FLAGS
                                              "-DENABLE_SHANI -msse4 -msha")
 set_source_files_properties(sha256_sse41.cpp PROPERTIES COMPILE_FLAGS
                                              "-DENABLE_SSE41 -msse4.1")
 set_source_files_properties(sha256.cpp PROPERTIES COMPILE_FLAGS
                                        "-DUSE_ASM -DENABLE_SHANI \
-                                       -DENABLE_SSE41 -DENABLE_AVX2")
+                                       -DENABLE_SSE41")
```

This will probably negatively impact performance, but it will hopefully allow you to get the code compiling!

**Comment by theuni** [comment] 2022-02-07 18:12
Yep, CMake should learn to run checks for these rather than assuming the target arch.

**Comment by Pi-Runner** [comment] 2022-02-08 00:01
Thanks,

Where would I paste. The patch code?

Hugh

**Comment by HalosGhost** [comment] 2022-02-08 00:33
You would download that to a file in the repository's root directory (e.g., named `no-avx.patch`), and then do the following:

```console
$ git apply no-avx.patch
```

You can read more about using `git-apply` on the official [`git` documentation](https://git-scm.com/docs/git-apply).

**Comment by Pi-Runner** [comment] 2022-02-08 01:46
Thanks, I’ll give it a try

**Comment by HalosGhost** [comment] 2022-02-09 17:50
I opened a new issue so we can track a more systemic fix to this problem, and so will be closing this one as a duplicate of #42.

**Closed as completed by HalosGhost** 2022-02-09 17:50 UTC
Labels: fix/bug, closed/duplicate
